import * as fs from "fs/promises";
import * as path from "path";
import { collectRuntimePaths, hasRuntimeSignals } from "@/lib/runtime-signals";
import type { ScaffoldPreview } from "@/lib/types";

type PathMap = Record<string, string>;

interface PlanforgeIndex {
  generatedBy?: string;
  rootFiles: PathMap;
  directories: PathMap;
  planning: PathMap;
  exports: PathMap;
  ai: PathMap;
  // Optional: agent-planforge drops this block once the runner/handoff vision
  // is removed (Phase 3). Every other block above is required by isPlanforgeIndex.
  handoff?: PathMap;
}

// Rule: every index-derived path in this shape must be produced by
// resolveArtifactPath (the containment guard's single choke point) -- never
// path.join(tempDir, ...) directly from a raw index entry.
export interface ResolvedPlanforgeOutputPaths {
  hasIndex: boolean;
  indexPath: string | null;
  tasksDir: string;
  architecturePath: string;
  scaffoldkitInputPath: string;
  planOutputPath: string;
}

const PLANNING_BASELINE: ScaffoldPreview = {
  status: "planning-baseline",
  label: "Planning baseline only",
  summary:
    "Plan, tasks, architecture, and agent guidance are ready. Resolve any wave-0 scaffold-fit review before relying on the generated structure for implementation.",
};

const FULL_SCAFFOLD: ScaffoldPreview = {
  status: "full",
  label: "Full scaffold",
  summary: "The initial repository structure is scaffolded and ready for implementation.",
};

function isPathMap(value: unknown): value is PathMap {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }

  return Object.values(value).every((entry) => typeof entry === "string" && entry.length > 0);
}

function isPlanforgeIndex(value: unknown): value is PlanforgeIndex {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return false;
  }

  const candidate = value as PlanforgeIndex;
  return (
    candidate.generatedBy === "agent-planforge" &&
    isPathMap(candidate.rootFiles) &&
    isPathMap(candidate.directories) &&
    isPathMap(candidate.planning) &&
    // handoff is optional: agent-planforge stopped emitting the runner/handoff
    // block (Phase 3). Accept an index with no handoff key, but still validate
    // it when present so a malformed block is rejected.
    (candidate.handoff === undefined || isPathMap(candidate.handoff)) &&
    isPathMap(candidate.exports) &&
    isPathMap(candidate.ai)
  );
}

async function readPlanforgeIndex(indexPath: string): Promise<PlanforgeIndex | null> {
  try {
    const raw = await fs.readFile(indexPath, "utf-8");
    const parsed = JSON.parse(raw) as unknown;
    return isPlanforgeIndex(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function resolveArtifactPath(
  tempDir: string,
  relativePath: string | undefined,
  fallbackPath: string,
  indexKey: string
): string {
  if (!relativePath) {
    return fallbackPath;
  }

  const candidate = path.join(tempDir, relativePath);

  // Containment guard: planforge-index.json is generated by the same session's
  // planforge tarball today, but nothing here re-validates it, and several
  // callers mirror the resolved artifact's contents verbatim into API responses
  // (e.g. architectureOverview in app/api/generate/route.ts and lib/v1-shared.ts).
  // A `../`-laden entry would otherwise let resolveArtifactPath point outside
  // tempDir at any file the process can read. (An absolute-looking entry, e.g.
  // "/etc/passwd", was already contained before this guard too: path.join
  // re-roots a subsequent absolute segment under tempDir instead of treating it
  // as absolute, so this guard specifically closes the `../` traversal class.)
  // Compare fully resolved (symlink-unaware — nothing else in this module
  // realpaths its inputs either, so lexical containment matches the rest of
  // the module's trust model; a symlink placed inside tempDir that points
  // outside it is still followed) paths with a trailing separator appended to
  // the temp dir side, so a sibling directory that merely shares the same
  // string prefix (e.g. "/tmp/session-evil" vs "/tmp/session") is never
  // mistaken for "inside".
  const resolvedTempDir = path.resolve(tempDir);
  const resolvedCandidate = path.resolve(candidate);
  const isContained =
    resolvedCandidate === resolvedTempDir || resolvedCandidate.startsWith(resolvedTempDir + path.sep);

  if (!isContained) {
    // Signal the rejection without leaking the attacker-controlled path value
    // into shared logs -- name only the offending index key, matching the
    // key-only logging discipline app/api/generate/route.ts already applies
    // to attachment names.
    console.warn(`planforge-index ${indexKey} escaped the session dir; using default`);
  }

  return isContained ? candidate : fallbackPath;
}

export async function resolvePlanforgeOutputPaths(tempDir: string): Promise<ResolvedPlanforgeOutputPaths> {
  const indexPath = path.join(tempDir, "planforge-index.json");
  const index = await readPlanforgeIndex(indexPath);

  if (!index) {
    return {
      hasIndex: false,
      indexPath: null,
      tasksDir: path.join(tempDir, "tasks"),
      architecturePath: path.join(tempDir, "architecture-overview.md"),
      scaffoldkitInputPath: path.join(tempDir, "scaffoldkit-input.json"),
      planOutputPath: path.join(tempDir, "plan-output.json"),
    };
  }

  return {
    hasIndex: true,
    indexPath,
    tasksDir: resolveArtifactPath(
      tempDir,
      index.directories?.tasks,
      path.join(tempDir, "tasks"),
      "directories.tasks"
    ),
    architecturePath: resolveArtifactPath(
      tempDir,
      index.rootFiles?.architecture,
      path.join(tempDir, "architecture-overview.md"),
      "rootFiles.architecture"
    ),
    scaffoldkitInputPath: resolveArtifactPath(
      tempDir,
      index.exports?.scaffoldkit,
      path.join(tempDir, "scaffoldkit-input.json"),
      "exports.scaffoldkit"
    ),
    planOutputPath: resolveArtifactPath(
      tempDir,
      index.planning?.planOutput,
      path.join(tempDir, "plan-output.json"),
      "planning.planOutput"
    ),
  };
}

export async function readScaffoldPreview(tempDir: string): Promise<ScaffoldPreview> {
  const artifacts = await resolvePlanforgeOutputPaths(tempDir);

  try {
    const raw = await fs.readFile(artifacts.scaffoldkitInputPath, "utf-8");
    const parsed = JSON.parse(raw) as {
      blueprintConfidence?: string;
      agentMustCreateStructure?: boolean;
    };

    if (parsed.agentMustCreateStructure || parsed.blueprintConfidence === "weak") {
      return PLANNING_BASELINE;
    }

    // A strong blueprint selection is not enough: if the scaffold emitted no real
    // source (only a manifest plus empty dirs), it is a planning baseline, not a
    // "full scaffold". Reuse the exact source-file signal #82 added to the
    // post-scaffold review verdict so the preview label and the verdict agree.
    const runtimeIndicators = await collectRuntimePaths(tempDir);
    if (!hasRuntimeSignals(runtimeIndicators)) {
      return PLANNING_BASELINE;
    }

    return FULL_SCAFFOLD;
  } catch {
    return PLANNING_BASELINE;
  }
}

// Generation-only planforge artifacts: downstream tools read these at
// generation time (planforge resume reads plan-output.json; scaffoldkit and
// project-forge read scaffoldkit-input.json before publish), but they have no
// value once committed into the deliverable. They are kept out of the published
// repo via .git/info/exclude, which is local to the temp clone and so never
// collides with scaffoldkit's own committed root .gitignore.
// The entire planning/ directory is planforge generation/replanning state
// (plan-output.json + structured-input.json + rerun-report.json +
// rerun-summary.md). Downstream tools read these at generation time from disk
// before publish, so none of it belongs in the committed deliverable.
export const PLANFORGE_PUBLISH_EXCLUDES = [
  "/planning/",
  "/exports/scaffoldkit-input.json",
];

export async function excludePlanforgeArtifactsFromPublish(projectDir: string): Promise<void> {
  // Derive the actual artifact locations from the generated index so the
  // exclude list tracks whatever layout planforge emits (e.g. a future move
  // under .planforge/) instead of drifting from hardcoded paths. Fall back to
  // the current default paths only when no index is present.
  const resolved = await resolvePlanforgeOutputPaths(projectDir);
  const toPattern = (absolutePath: string) =>
    `/${path.relative(projectDir, absolutePath).split(path.sep).join("/")}`;
  // Exclude the whole planning/ directory (the parent of plan-output.json) so
  // structured-input.json + rerun-report.json + rerun-summary.md and any future
  // planning-only artifact are kept out too, not just plan-output.json. Guard
  // against a flat layout where plan-output.json sits at the repo root: never
  // turn that into a "/" exclude that would drop the entire deliverable.
  let excludes: string[];
  if (resolved.hasIndex) {
    const planningRel = path
      .relative(projectDir, path.dirname(resolved.planOutputPath))
      .split(path.sep)
      .join("/");
    const planningDirPattern =
      planningRel && !planningRel.startsWith("..")
        ? `/${planningRel}/`
        : toPattern(resolved.planOutputPath);
    excludes = [planningDirPattern, toPattern(resolved.scaffoldkitInputPath)];
  } else {
    excludes = PLANFORGE_PUBLISH_EXCLUDES;
  }

  // Never emit a bare "/" (or empty) pattern: a degenerate index value such as
  // planOutput="." would resolve the planning directory to the repo root. A
  // bare "/" is a git no-op in practice, but drop it defensively so the exclude
  // block can never target the whole deliverable.
  excludes = excludes.filter((pattern) => pattern && pattern !== "/");

  const excludePath = path.join(projectDir, ".git", "info", "exclude");
  await fs.mkdir(path.dirname(excludePath), { recursive: true });
  const existing = await fs.readFile(excludePath, "utf-8").catch(() => "");
  const block = [
    "# planforge generation-only artifacts (kept out of the deliverable)",
    ...excludes,
  ].join("\n");
  if (existing.includes(block)) {
    return;
  }
  const next = existing.trim()
    ? `${existing.replace(/\n+$/, "")}\n${block}\n`
    : `${block}\n`;
  await fs.writeFile(excludePath, next);
}

// Reconcile the committed planforge-index.json with what actually ships. The
// generation-only artifacts excludePlanforgeArtifactsFromPublish keeps out of the
// commit (the whole planning/ directory + exports/scaffoldkit-input.json) are not
// in the deliverable, so an agent or tool that trusts the index for path discovery
// would 404 on those entries. Drop them from the SHIPPED index here. This must run
// AFTER excludePlanforgeArtifactsFromPublish, which reads the complete index to
// derive its patterns, so the generation-time index on disk stays intact for that.
export async function prunePublishedPlanforgeIndex(projectDir: string): Promise<void> {
  const indexPath = path.join(projectDir, "planforge-index.json");
  const index = await readPlanforgeIndex(indexPath);
  if (!index) {
    return;
  }

  // exports/scaffoldkit-input.json is the only excluded exports entry; other
  // exports (e.g. devreview, when planforge still emits it) ship and stay.
  const exports: PathMap = { ...(index.exports ?? {}) };
  delete exports.scaffoldkit;

  const directories: PathMap = { ...(index.directories ?? {}) };
  // The entire planning/ directory is excluded from publish.
  delete directories.planning;
  // exports/ is committed only when a non-excluded exports entry survives; if
  // scaffoldkit-input.json was the only one, the directory is absent from the commit.
  if (Object.keys(exports).length === 0) {
    delete directories.exports;
  }

  // Preserve every other field (version, summary, context, rootFiles, ai,
  // handoff, ...); only the excluded blocks are pruned. planning is emptied
  // rather than deleted so the index keeps its documented shape.
  const pruned = {
    ...index,
    directories,
    planning: {},
    exports,
  };

  await fs.writeFile(indexPath, `${JSON.stringify(pruned, null, 2)}\n`);
}
