import { NextRequest, NextResponse } from 'next/server';
import { randomUUID } from 'crypto';
import { spawn } from 'child_process';
import * as fs from 'fs/promises';
import * as path from 'path';
import type {
  ProjectInput,
  GenerateResponse,
  ErrorResponse,
  Task,
  FileTreeNode,
} from '../../../lib/types';

const TEMP_ROOT = process.env.FORGE_TEMP_DIR ?? '/tmp/project-forge';
const PLANFORGE_PATH = process.env.PLANFORGE_PATH ?? '/root/.openclaw/workspace/git/agent-planforge';
const SCAFFOLDKIT_PATH = process.env.SCAFFOLDKIT_PATH ?? '/root/.openclaw/workspace/git/scaffoldkit';
const GENERATION_TIMEOUT_MS = 30_000;

export async function POST(req: NextRequest) {
  let sessionId: string | null = null;

  try {
    const input: ProjectInput = await req.json();

    if (!input.projectName || !input.summary) {
      return NextResponse.json<ErrorResponse>(
        { ok: false, error: 'Missing required fields: projectName, summary' },
        { status: 400 }
      );
    }

    sessionId = randomUUID();
    const tempDir = path.join(TEMP_ROOT, sessionId);
    await fs.mkdir(tempDir, { recursive: true });

    // Step 1: Run planforge
    const planforgeInput = {
      projectName: input.projectName,
      summary: input.summary,
      targetUsers: input.targetUsers ?? ['developers'],
      coreFeatures: (input.features && input.features.length > 0) ? input.features : ["core functionality"],
      constraints: input.constraints ?? [],
    };

    const inputPath = path.join(tempDir, 'project-input.json');
    await fs.writeFile(inputPath, JSON.stringify(planforgeInput, null, 2));

    await runCommand(
      'node',
      [
        path.join(PLANFORGE_PATH, 'scripts', 'bootstrap-plan.js'),
        '--input',
        inputPath,
        '--outdir',
        tempDir,
        '--no-install',
      ],
      tempDir,
      GENERATION_TIMEOUT_MS
    );

    // Step 2: Run scaffoldkit from-planforge (reads scaffoldkit-input.json generated by planforge)
    const scaffoldkitInputPath = path.join(tempDir, 'scaffoldkit-input.json');
    // Write scaffold files directly into tempDir (not a subdirectory)
    // so they appear at repo root when pushed to GitHub
    const scaffoldkitPython = process.env.SCAFFOLDKIT_PYTHON ?? '/tmp/sk-venv/bin/python3';

    const scaffoldkitExists = await fs.access(scaffoldkitInputPath).then(() => true).catch(() => false);
    if (scaffoldkitExists) {
      await runCommand(
        scaffoldkitPython,
        [
          '-m', 'scaffoldkit.cli',
          'from-planforge',
          scaffoldkitInputPath,
          '--target', tempDir,
          '--no-install',
        ],
        tempDir,
        GENERATION_TIMEOUT_MS
      ).catch((err: Error) => {
        // scaffoldkit failure is non-blocking — planforge output is still useful
        console.error('scaffoldkit FAILED:', err.message);
      });
    }

    // Parse planforge output
    const tasksDir = path.join(tempDir, 'tasks');
    const archPath = path.join(tempDir, 'architecture-overview.md');

    const taskFiles = (await fs.readdir(tasksDir).catch(() => [])).filter(
      (f) => f.endsWith('.md')
    );

    const tasks: Task[] = await Promise.all(
      taskFiles.map(async (file) => {
        const content = await fs.readFile(path.join(tasksDir, file), 'utf-8');
        const idMatch = file.match(/^(\d+)-/);
        const titleMatch = content.match(/# Task \d+[:\s]+(.+)/);
        const waveMatch = content.match(/## Wave\s*\n\s*\n\s*(.+)/);
        const categoryMatch = content.match(/## Category\s*\n\s*\n\s*(.+)/);
        const priorityMatch = content.match(/## Priority\s*\n\s*\n\s*(.+)/);
        const summaryMatch = content.match(/## Summary\s*\n\s*\n\s*(.+)/);
        return {
          id: idMatch?.[1] ?? file.replace('.md', ''),
          title: (titleMatch?.[1] ?? file).trim(),
          wave: (waveMatch?.[1] ?? 'wave-1').trim(),
          category: (categoryMatch?.[1] ?? 'feature').trim(),
          priority: (priorityMatch?.[1] ?? 'P1').trim(),
          summary: summaryMatch?.[1]?.trim(),
        };
      })
    );

    const architectureOverview = await fs
      .readFile(archPath, 'utf-8')
      .catch(() => '(Architecture overview not generated)');

    const fileTree = await buildFileTree(tempDir);

    const waves = new Set(tasks.map((t) => t.wave));

    const response: GenerateResponse = {
      ok: true,
      preview: {
        sessionId,
        projectName: input.projectName,
        tasks,
        architectureOverview,
        fileTree,
        taskCount: tasks.length,
        waveCount: waves.size,
      },
    };

    return NextResponse.json(response);
  } catch (error: any) {
    console.error('Generation failed:', error);

    if (sessionId) {
      const tempDir = path.join(TEMP_ROOT, sessionId);
      await fs.rm(tempDir, { recursive: true, force: true }).catch(() => {});
    }

    return NextResponse.json<ErrorResponse>(
      {
        ok: false,
        error: 'Failed to generate project',
        details: error.message,
      },
      { status: 500 }
    );
  }
}

function runCommand(
  cmd: string,
  args: string[],
  cwd: string,
  timeout: number
): Promise<void> {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, {
      cwd,
      shell: false,
      timeout,
    });

    let stdout = '';
    let stderr = '';

    proc.stdout?.on('data', (data) => {
      stdout += data.toString();
    });

    proc.stderr?.on('data', (data) => {
      stderr += data.toString();
    });

    proc.on('error', (err) => {
      reject(new Error(`Failed to execute ${cmd}: ${err.message}`));
    });

    proc.on('exit', (code) => {
      if (code === 0) {
        console.log(`${cmd} output:`, stdout);
        if (stderr) console.warn(`${cmd} stderr:`, stderr);
        resolve();
      } else {
        reject(
          new Error(`${cmd} exited with code ${code}\nStdout: ${stdout}\nStderr: ${stderr}`)
        );
      }
    });
  });
}

async function buildFileTree(
  dirPath: string,
  basePath = ''
): Promise<FileTreeNode[]> {
  const entries = await fs.readdir(dirPath, { withFileTypes: true });
  const nodes: FileTreeNode[] = [];

  // Skip certain directories
  const skipDirs = new Set(['node_modules', '.git', 'venv', '__pycache__']);

  for (const entry of entries) {
    if (skipDirs.has(entry.name)) continue;

    const relativePath = basePath ? `${basePath}/${entry.name}` : entry.name;
    const fullPath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      const children = await buildFileTree(fullPath, relativePath);
      nodes.push({
        name: entry.name,
        path: relativePath,
        type: 'directory',
        children,
      });
    } else {
      nodes.push({
        name: entry.name,
        path: relativePath,
        type: 'file',
      });
    }
  }

  return nodes.sort((a, b) => {
    if (a.type === 'directory' && b.type === 'file') return -1;
    if (a.type === 'file' && b.type === 'directory') return 1;
    return a.name.localeCompare(b.name);
  });
}

