name: CI

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "20"
          cache: "npm"
      - run: npm ci --legacy-peer-deps --no-audit --no-fund
      - run: npx prisma generate
      - run: npx tsc --noEmit --skipLibCheck
      - run: npm run lint
      - run: npm run build
        env:
          GITHUB_TOKEN: "mock"
          GITHUB_OWNER: "mock"
      - run: npm run test:coverage
